In [1]:
import numpy as np
x = [3,2,4,5,1]
x = np.array(x)
x

array([3, 2, 4, 5, 1])

In [2]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [3]:
np.sort(x)[::-1]

array([5, 4, 3, 2, 1])

In [5]:
x = [3,2,4,5,1]
for i in range(len(x),0,-1):
    for j in range (0, i-1):
        if x[j] > x[j+1]:
            x[j],x[j+1] = x[j+1], x[j]
    
print (x)

[1, 2, 3, 4, 5]


In [6]:
x = [3,2,4,5,1]
for i in range(len(x),0,-1):
    for j in range (0, i-1):
        if x[j] < x[j+1]:
            x[j],x[j+1] = x[j+1], x[j]
    
print (x)

[5, 4, 3, 2, 1]


In [7]:
z = [[9,10,2], [5,1,4]]
z = np.array(z)
np.sort(z)

array([[ 2,  9, 10],
       [ 1,  4,  5]])

In [8]:
np.sort(z, axis=0)

array([[ 5,  1,  2],
       [ 9, 10,  4]])

In [9]:
np.sort(z, axis=1)

array([[ 2,  9, 10],
       [ 1,  4,  5]])

In [10]:
np.sort(z, axis=None)

array([ 1,  2,  4,  5,  9, 10])

In [11]:
x = np.arange(1,10).reshape(3,-1)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
print(x[:, [1,0,2]])

[[2 1 3]
 [5 4 6]
 [8 7 9]]


In [13]:
print(x[[1,0,2], :])

[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [14]:
print (x[[0,0,0], :])
print ("\n")
print (x[: , [0,0,0]])

[[1 2 3]
 [1 2 3]
 [1 2 3]]


[[1 1 1]
 [4 4 4]
 [7 7 7]]


In [15]:
a = np.array ([
    [1,2], [3,4], [5,6]
])
print (a)

[[1 2]
 [3 4]
 [5 6]]


In [16]:
print (a.transpose())

[[1 3 5]
 [2 4 6]]


In [30]:
x = np.loadtxt("nov29.csv", skiprows=1, delimiter=",", unpack=True)
print (x)

[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [20. 22. 24. 25. 20. 21. 28. 27.]]


In [31]:
id, usia = np.loadtxt("nov29.csv", skiprows=1, delimiter=",", unpack=True)
print (id)
print (usia)

[1. 2. 3. 4. 5. 6. 7. 8.]
[20. 22. 24. 25. 20. 21. 28. 27.]


In [32]:
np.savetxt("nov29b.csv", usia, fmt="%d", header="usia", comments="")

In [33]:
c = np.vstack([id,usia]).transpose()
print (c)

[[ 1. 20.]
 [ 2. 22.]
 [ 3. 24.]
 [ 4. 25.]
 [ 5. 20.]
 [ 6. 21.]
 [ 7. 28.]
 [ 8. 27.]]


In [34]:
np.savetxt("nov29c.csv", c, fmt="%d", header="id,usia", comments="", delimiter=",")

In [35]:
data1 = np.array(list(map(lambda a,b: [a,b], id, usia)))

print (data1)

[[ 1. 20.]
 [ 2. 22.]
 [ 3. 24.]
 [ 4. 25.]
 [ 5. 20.]
 [ 6. 21.]
 [ 7. 28.]
 [ 8. 27.]]
