In [2]:
import numpy as np
x = [3, 2, 4, 5, 1]
y = np.array(x)
y

array([3, 2, 4, 5, 1])

In [27]:
x.sort(reverse=True)
x

In [4]:
np.sort(y)[::-1]

array([5, 4, 3, 2, 1])

In [29]:
def descSort(param):
    newList = list(param)
    for i in range(len(newList)-1):
        for j in range(i+1, len(newList), 1):
            if newList[i] < newList[j]:
                newList[i], newList[j] = newList[j], newList[i]
    return newList

descSort(x)


[5, 4, 3, 2, 1]

In [30]:
def ascSort(param):
    newList = list(param)
    for i in range(len(newList)-1):
        for j in range(i+1, len(newList), 1):
            if newList[i] > newList[j]:
                newList[i], newList[j] = newList[j], newList[i]
    return newList

ascSort(x)



[1, 2, 3, 4, 5]

In [3]:
z = [
    [9, 10, 2],
    [5, 1, 4]
]
z = np.array(z)
np.sort(z, axis = 0)

array([[ 5,  1,  2],
       [ 9, 10,  4]])